### ISSUE TITLE
Adding some features to the plugin without breaking (almost) the existing functionnality

### ISSUE THREAD

**Issue by juliendms** [RestlessThinker/danger-jira#18]
Hello,

I found out your plugin as we are trying to implement Danger in our environment where we use Jira. We would like to be able to perform the following actions with the plugin :

## Ability to search also in branch name

Usually, we use the title of our MR/PRs to describe the problem and build our release note. So we use the branch name to reference the JIRA ticket number, like for example: `bugfix/KEY-123`. An additional option to search the branch name would be nice.

## Ability to connect to the JIRA API

For the two next features, we would need to access the JIRA API. To keep the call of the main method short, I thought about using ENV variables of the CI environment just like Danger do to store Gitlab/Github token and url. Eg. `DANGER_JIRA_TOKEN` and `DANGER_JIRA_URL`.

## Ability to pull out the title in the message of Danger

If `DANGER_JIRA_TOKEN` is not empty, it would be interesting to insert the title (summary) of the JIRA ticket in the message posted by Danger (see #16)

## Ability to transition the issue

Add another optional parameter in the main method (transition_id) to automatically transition the referenced JIRA issue(s) when the MR is opened. The nice thing would be to post a warning message if the transition fails (something that is actually not supported by JIRA smart commits).

What do you think about this ? I am still pretty newbie to Ruby, but I can contribute to the best of my knowledge if you think those features could be a nice addition to this plugin.

**Comment by RestlessThinker** [comment]
Hello @juliendms,

Thank you for your PR! I've shipped it with `0.9.0` of the plugin. As for your other inquiries, I'm going to mark them as `Will not implement` for now as those can probably be done with a GitHub Action and this plugin should attempt to be as focused and lightweight as possible. Thanks again for your contributions! 🚀
